services:
  ocr-contracts:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    restart: unless-stopped
    networks:
      - app-network

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - /Users/myszon/Projects/ocr_contracts/test_data:/home/node/data
    environment:
      - N8N_RUNNERS_ENABLED=true
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  n8n_data: